/*
 * TIMER0.c
 *
 * Created: 2/17/2023 4:19:59 PM
 *  Author: amrkh
 */ 

#include "TIMER0.h"
#include <avr/io.h>



void TIMER0_CTC_INIT_INTERRUPT()
{	
	/*CTC MODE ENABLE*/
	SET_BIT(TCCR0 , WGM01);
	
	OCR0 = 18;
	
	/*CONFIGURE CLOCK SELECT PINS*/
	SET_BIT(TCCR0 , CS02);
	
	/*SET I BIT*/
	SET_BIT(SREG , I_BIT);
	
	/*SET OUTPUT COMPARE MATCH ENABLE BIT FOR TIMER0*/
	SET_BIT(TIMSK , OCIE0);
	
	
}

void TIMER_WAVE_GENERATION_NON_PWM()
{	
	/*CTC MODE*/
	SET_BIT(TCCR0 , WGM01);
	
	/*CLOCK SELECT 1024*/
	SET_BIT(TCCR0 , CS00);
	SET_BIT(TCCR0 , CS02);
	
	OCR0 = 64;
	
	/*TOGGLE SIGNAL IN OC0 ON COMPARE MATCH*/
	SET_BIT(TCCR0 , COM00);
	
	/*CONFIGURE OC0 AS OUTPUT PIN*/
	DIO_SET_PIN_DIR('B',3,1);
	
	
}

void TIMER_WAVE_FAST_PWM()
{
	/*FAST PWM MODE*/
	SET_BIT(TCCR0 , WGM00);
	SET_BIT(TCCR0 , WGM01);
	
	
	/*CLOCK SELECT 1024*/
	SET_BIT(TCCR0 , CS00);
	SET_BIT(TCCR0 , CS02);
	
	
	/*CONF. DUTY CYCLE TO 25%*/
	OCR0 = 64;
	
	/*CONFIGURE OC0 AS OUTPUT PIN*/
	DIO_SET_PIN_DIR('B',3,1);
	
	
	/*CONF. COM PINS TO CLEAR ON CM AND SET ON BOTTOM*/
	SET_BIT(TCCR0 , COM01);

}


void TIMER_WAVE_PHASE_CORRECT_PWM()
{
	/*PHASE CORRECT PWM MODE*/
	SET_BIT(TCCR0 , WGM00);
	
	/*CLOCK SELECT 1024*/
	SET_BIT(TCCR0 , CS00);
	SET_BIT(TCCR0 , CS02);
	
	
	/*CONF. DUTY CYCLE TO 25%*/
	OCR0 = 64;
	
	/*CONFIGURE OC0 AS OUTPUT PIN*/
	DIO_SET_PIN_DIR('B',3,1);
	
	
	/*CONF. COM PINS TO CLEAR ON UPCOUNTING AND SET ON DOWNCOUNTING*/
	SET_BIT(TCCR0 , COM01);
	
}